# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 047c0ce0ab6b210948bd05496e28dfa2e431dbc322b2323f6831bb742619139d61eeefd364630edb78ad02471f9ef02d02df95c1ca116a16d1cf503fee03fac3

test:
  secret_key_base: af342b701fb4b2950b3c06d3b4f4afb232b77f31a8f824c81f91d90d0d226be16b69846dbde56df97a05d7ad15932cd28c034f6d659c8bcafc85efb84c9a4fdb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
